version: '3'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_cashflow
      MYSQL_ROOT_HOST: '%'
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql    
    ports:
      - '3306:3306'
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    labels:
      kompose.service.type: nodeport       
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
        - 'rabbitmq_data:/bitnami' 
  web:
    image: restcashflowwebapi
    build:
      context: .
    restart: on-failure
    healthcheck:
        test: 'curl --silent --fail http://localhost:3000/swagger || exit 1'
        interval: 5s
        timeout: 10s
        retries: 5
    ports:
      - '3000:80'
    depends_on:
        - mariadb
        - rabbitmq
    links:
        - mariadb
        - rabbitmq
    environment:
        - ASPNETCORE_ENVIRONMENT=Production 
volumes:
    rabbitmq_data:
